### ISSUE TITLE
penalties/forfeitures

### ISSUE THREAD

**Issue by dbinetti** [barberscore/barberscore-api#400]
Additional penalities/forfeitures as discussed previously

**Comment by dbinetti** [comment]
Actually, I felt we were done with this.  so please be more specific.  what are the conditions?  I may have simply forgotten

**Comment by dbinetti** [comment]
[Uploading CJBook-16 Penalties & Forfeitures.pdf…]()

**Comment by dbinetti** [comment]
[CJBook-16 Penalties & Forfeitures.pdf](https://github.com/barberscore/barberscore-api/files/2952520/CJBook-16.Penalties.Forfeitures.pdf)

**Comment by dbinetti** [comment]
I need to dig this out of my brain.  My recollection is that the remaining penalties were so rare and special that we could handle them manually with footnotes and back-end munging.  But let me review the actual penalties and re-think

**Comment by CLBuechler2324** [comment]
Need to add disqualification forfeitures that remove group from OSS. A footnote does not work if group disqualified.

**Comment by dbinetti** [comment]
Who does the DQing?  Is this a "the CA needs to do it before the Round is Verified and Published" thing, or is it a "after the fact" thing.  Or potentially both?

**Comment by millsjdm** [comment]
Clarification of Requirements:
- While all penalties will be noted in the group's appearance record, only penalties of 5 or more points (per judge) will be "flagged" and a footnote appear on the OSS and CSA. Here is the current list of the 10 possible penalties that could occur during the contest session and the appropriate "<string>" to be indicated on the OSS/CSA:
"Penalized for violation of the BHS Contest Rules: <string>
< Article V.A.2 >
< Article VIII.B >
< Article IX.A.1 (Patriotic) >
< Article IX.A.1 (Religious) >
< Article IX.A.2 >
< Article IX.A.3 >
< Article X.B.1 >
< Article X.B.2 >
< Article X.B.3 >
< Article XI.C >
These 6 additional ones are handled differently. Instead of an asterisk next to the song, the group is disqualified and completely removed from the OSS. The footnote should indicate their disqualification as follows:
"<group_name> disqualified due to violation of the BHS Contest Rules: <string>
< Article I.A >
< Article I.B.1 >
< Article I.B.2 >
< Article I.B.3 >
< Article I.B.8 >
< Article XI.A.1 >

- POST CONTEST (after the original OSS has been published): Up to 30 days following a contest weekend, an amended OSS may need to be created and distributed for the official record to reflect a disqualification for other possible rule violations. These can be created manually by a Barberscore Admin (since this would be extremely rare).

**Comment by dbinetti** [comment]
OK, time to put some meat on the bones.

From what I can tell reading this and the actual rules, it appears that all
of the Penalties are applied by the CA in real-time.  Currently, we only
handle (IX.A.1 [both variants, no distinction between them]), IX.A.2,
IX.A.3 and X.B.3 [which we imprecisely characterize as X.B]).  That said, I
should mention that when these are checked they appear on the OSS -- there
is no specific provision for keeping the actual penalty, and no
determination if it is >5 points.  So if that is a new requirement we need
to build that in.

I'll address the other penalties below:

These penalties can be handled via the same mechanism as the ones that
we've already implemented:
- X.B.1, X.B.2, XI.C, V.A.2 and VIII.B.

By this, I mean, all we need to do is add them to the dropdown.  However,
this also assumes that the CA will do the scoring reductions manually.  If
the scoring adjustments must be built in, I can do that also -- but it is
***CRITICAL*** that we pick one method or the other and train the CAs
accordingly.  Otherwise double-counting or missing will occur.   This does
assume, again, that we need not track the actual penalty, but only indicate
that one has happened.

For the "Below the Line" items (ie, the DQs), these all appear to be
after-the-fact processes, handled not by the CA but some other process. If
this is true, then I would simply say that we have the Barberscore Admin
handle it.  yes, I will still create a framework for choosing the DQ state
and the corresponding violation, but it's something that can be handled
without immediacy.

Please confirm all this.  Phone call works if too complicated to go over in
email.

**Comment by millsjdm** [comment]
Call me... I'm available all evening! Meanwhile - some specific answers:
1) The only time a CA would have to manually change a score that was provided by a judge would be for: V.A.2, VIII.B, XI.C. In these instances, they are either entering a '0' for every judge's score (V.A.2), or they are reducing each judge's score by 5 points (VIII.B & XI.C). I don't see any reason why we can't just expect them to do that manually - that is what they do now in legacy (I think).
2) Our current policies dictate that only penalties of 5 points or more ever "show up" on the OSS. In the legacy software, when judge's indicate a penalty for less than 5 points, CAs make note of the Article # (for their reports), but they don't create a flag to show it on the OSS. I'm perfectly okay with training our CAs to simply ignore all penalties (less than 5 points) they see on judge's score sheets as far as Barberscore is concerned. We can ask them instead to track those in a separate report. But ideally, we're going to want to "capture" that information in Barberscore to be associated with the group's appearance - (as we are able to do now with variance score info). So... if you can do it easily - great! If not - low priority.
3) Those 6 "DQs" that I listed would MOST LIKELY happen post-contest - if ever - (which requires an amended OSS as I mentioned). However, those particular 6 COULD become apparent prior to the closing of a contest round - (for example the DRCJ comes to notify the CA that they must DQ a competitor that sang 30 minutes ago because of a discovered ineligibility issue). In those cases (as mentioned above) - the competitor must be redacted completely from the OSS, and we need that footnote to explain why. Admittedly, this is rare. In fact, it it so rare that I can propose perhaps an easier "workaround":
Ask the CAs to treat these use cases similar to V.A.2 (simply select the Article from the drop-down, then put a '0' for every judge's score). The only difference will be the verbiage of the footnote (which should indicate that they were in fact disqualified). While they'd still "appear" on the OSS, the spirit of the current policy would still be honored.

**Comment by CLBuechler2324** [comment]
1. No, legacy automatically adjusts ALL scores to 0 for any song with unanimous MUS judge scores of 0 (V.A.)  It automatically adjusts -5 for every score for int’l staging (XI.C) and for VIII.B (unexcused late) although i have never seen either implemented.
3. Art I & XI.DQ’s normally are done on site immediately, not after the fact.  

Based on what I’ve seen recently I’m less confident that CAs can do math on own. 😳 But we certainly can try.

**Comment by dbinetti** [comment]
1.  Doing automatic calculations are what computers are good at.  I agree with Chris; if even "good" CAs are missing things AS OBVIOUS AS INSTRUCTIONS IN ALL CAPS  remembering to do manual adjustments is not something we should try as a *new* responsibility.  If they were used to it, fine. If not, let the computer do its thing.

2.  So in the attached scoresheet, are the penalty amounts indicated accordingly?  And then the score is net of that?  So all I'd need to do is track the penalty and number, right?  The computer can flag from there.  I guess what would be ideal is a list of all the penalties and how the CA receives them -- ie, on the scoresheets, as a note from the DRCJ, etc.  The workflow dictates the UI and backend flow.  But let's not throw away info.

3.  Again, let's do it the right way.  We have enough technical debt; let's not add on.  But this is again mostly from a workflow perspective.  If the DRCJ is responsible for it, then perhaps the DRCJ should do it -- The Who is more important than the when.  One question is: are they DQ'd from all rounds?  If they are discovered in the finals, are they scrubbed from the semis?

**Comment by millsjdm** [comment]
1. Agreed
2. The penalties provided by the judge are just that - the actual penalty amount. (If less than 5 there is no footnote generated). The total score is their final score (after having factored in the penalty). The exception would likely be for a score forfeiture, in which they would probably just check the appropriate penalty box, but then put a zero (0) in the total score box.
Attached is the list of penalties and how they are "received" by the CA. {Please note an edit from the previous list of awards - I.B.8 is actually now I.B.7}
[PenaltiesWorkFlow.xlsx](https://github.com/barberscore/barberscore-api/files/3091359/PenaltiesWorkFlow.xlsx)

3. Answers are covered in the attached spreadsheet. However, DRCJs do not have authority to edit OSS reports. CAs are responsible for the application of all actions until the contest results have been determined and the OSS is published.

**Comment by CLBuechler2324** [comment]
I’m wondering about a Disqualification button (similar to Scratch) that would remove contestant from the original OSS vice having all zeros for both songs and a subsequent revised OSS.  That would solve a lot of the DQs.

**Comment by dbinetti** [comment]
No, we are not doing all zeros -- no hacks unless necessary.  The method will change the competitor state to "Disqualified" and remove them entirely from the OSS.  

But part of the reason I'm asking for the workflow is that I don't think we'll want a button on every appearance.  it will be super-cluttered for something that happens rarely in the first place and almost never during the contest itself.  

Still need an sewer to the question:  are they DQ'd from all rounds? If they are discovered in the finals, are they scrubbed from the semis?

**Comment by CLBuechler2324** [comment]
Interesting question.  In most cases disqualification is DQ from the contest. However, in case of Art.II.E. where an additional member appears in finals and contestant is disqualified then, I would argue the first appearance (in QS) is not disqualified.  That’s how it was handled last year in MAD (first & only time the article was used so far).

**Comment by CLBuechler2324** [comment]
All zeros would be appropriate for Art.V repeat song forfeiture with other song receiving scores.

Agree re not having buttons if avoidable.

**Comment by dbinetti** [comment]
But that's not a disqualification.  It's a 100% penalty.

**Comment by CLBuechler2324** [comment]
Correct - a forfeiture.

**Comment by millsjdm** [comment]
To answer your question "Are they DQd from all rounds", as Chris pointed out, almost always "yes". However (from a workflow perspective), I covered the details of that in the previously attached spreadsheet.

**Comment by CLBuechler2324** [comment]
Don’t see II.E.1 (change during contest) on spreadsheet

**Comment by millsjdm** [comment]
Yep, missed it.
II.E.1 (same as most other "during the contest" DQs) - except that the CA will only apply DQ for that round.

**Comment by dbinetti** [comment]
This is now in place.  In order to avoid clutter I've *not* added the DQ button in the front-end.  The admin will need to apply a disqualification on the back-end Appearance.  

Should the CA need to apply a DQ and the admin resource is not available, the workflow should be to Scratch the Competitor and manually add a footnote.  This will appear on the OSS identical to a DQ, and the actual state can be cleaned up later.
