### ISSUE TITLE
Penalty next to scores

### ISSUE THREAD

**Issue by dbinetti** [barberscore/barberscore-api#465]
we need to have the penalty footnote marker next to the actual scores that were impacted instead of the song

**Comment by dbinetti** [comment]
This is not going to be easy.  When we had our discussion on penalties so that I could build this we specifically settled on Songs as the object where non-DQ penalties are applied.  Putting them on another object impacts information architecture and will require me to change a lot.  And aren't these penalties assigned by category anyway?  What is the objective?

**Comment by millsjdm** [comment]
Thanks for the reminder about that discussion. So yes, since we're identifying which rule Article is involved, the category is identified through that. 
So... the song title is fine - although, perhaps have the footnote marker at the front of the song title instead? (Just in case the title/arranger string is too long)

**Comment by dbinetti** [comment]
The title/arranger string will always produce ellipses with enough space for the penalty marker; it's a different field.  So without objection I'm going to keep this as is.

**Comment by millsjdm** [comment]
Makes sense - sounds good. ☺

*J. David Mills*
SCJC Chairman 2016-2019
*Mobile Phone - 813.786.4381*

*Singing is Life is Singing is…*
