### ISSUE TITLE
1st Appearance after Starting Round

### ISSUE THREAD

**Issue by millsjdm** [barberscore/barberscore-api#495]
(From Chris): I was able to replicate an issue reported by several CAs - the first appearance after starting a round has only a Delete option.
<img width="615" alt="Screen Shot 2019-04-19 at 8 24 26 PM" src="https://user-images.githubusercontent.com/30165860/56460665-4797d600-6374-11e9-8c7b-50a16beb3154.png">

The work-around is to go to the Next - then go back - or do a browser refresh.

**Comment by dbinetti** [comment]
I've fixed this, but even though the workaround works the better workaround is to refresh the page.  This is better because it should always be the first thing we try when something goes wrong.  

First, refresh the page.  If it still doesn't work, then ask an admin.  

Of course, we should always file a bug report even if refreshing the page works.  But that should be the first step; it solves 90% of the problems related to getting out of state.
