### ISSUE TITLE
Advancing additional appearances (out of order)

### ISSUE THREAD

**Issue by CLBuechler2324** [barberscore/barberscore-api#499]
How does CA advance additional appearance below the 'black line' without picking up every other groups above it?  Case: DRCJ has decided OOD quartet will make finals but it doesn't score well.  Do not want to advance all in-disrict appearances above it.  
Used to be able to change Completed/Advanced in Competitor tab.  What now?

**Comment by dbinetti** [comment]
Solution depends on the goal.  If you need the OOD quartet to be in the Draw printed on the semi-finals round OSS then I'll need to build something new.  But if you simply want them added to the finals then create a new appearance for them in the Finals.  If their OA number is positive (ie, greater than zero) then everything will calculate normally.  

You could also simply add a manual footnote on the semis saying something like "FOOBAR quartet advanced due to OOD" or whatever.  But they still won't be part of the "official" draw.

Closing assuming that my solution works.  If it doesn't, comment and re-open

**Comment by CLBuechler2324** [comment]
I thought any appearance created as New in Finals would be Score/Eval Only. 
So you’re saying a new appearance with positive number is going to appear on finals OSS?

Unlikely to need this for OOD. But real situation is group that advances to finals, then withdraws and is replaced by another group in finals. How is that handled?

**Comment by dbinetti** [comment]
Correct, created as New in Finals is irrelevant.  The convention is:
- Any group with an OA as a positive number appears on the OSS
- Any group with a negative or zero number appears as a footnote as "score
eval/only"
If this is going to cause heartburn I can make this explicit.  seems like
that is where we should go.

WRT your scenario, you withdraw the group in the next round, and add a new
appearance.  If you want them scored, make it a positive draw, otherwise
negative.

The draw here is akin to the draw for international: it is done in advance,
and doesn't change once published.  Sure, the actual order winds up being
different, but what was published remains the same just like the order in
the program doesn't match what actually happens on stage....

**Comment by CLBuechler2324** [comment]
If you create new appearance in finals, will it pull semi-finals scores for total score?

**Comment by dbinetti** [comment]
yes, if the Appearance number is > 0
