### ISSUE TITLE
Create New Appearance not working

### ISSUE THREAD

**Issue by CLBuechler2324** [barberscore/barberscore-api#500]
Not working in staging.  Can't add at beginning or end of appearances.  Thought CA ws gouging o be able to rearrange; not working.

**Comment by dbinetti** [comment]
Fixed in b495725a

**Comment by CLBuechler2324** [comment]
Okay, can now Create at end of appearances and with negative numbers prior to MT.  But CA cannot rearrange draw. I thought that was going to be an option??

**Comment by dbinetti** [comment]
I can do this, but I think we concluded it wasn't worth the effort (at
least not for the time being.). The real question here is "what is the
publishing requirement"?

The only time that you *need* to rearrange the draw is prior to
publishing the round, so that the draw is accurately reported on the
OSS.  If that's not the requirement here, then the groups can sing in
whatever order they want; the CA is free to click Prev/Next or
directly on an appearance to his heart's content.  Obviously there is
no such thing as a "negative" appearance, just as there has never been
a "zero" appearance; they are merely a convention to simplify the
process.

**Comment by CLBuechler2324** [comment]
One practical problem is how to align the appearance (draw #) with the scoring forms for panel use (during contest and for evals).  The scoring forms will be numbered MT-XXX (MT = 0)  So while the CAs can enter scores based on quartet name, it’s confusing to panel when scoring form #7 is singing third...then it gets complicated.

**Comment by dbinetti** [comment]
Open #501
